modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="magicaltech"
version="1.0.6"
displayName="Magical Technology Base"
displayURL="https://modrinth.com/user/ezyybin604"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ezyybin604"
description="Can be used in a modrinth pack"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.magicaltech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.magicaltech]]
    modId="protection_pixel"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magicaltech]]
    modId="twilightforest"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration