chunks = false
base = true
quests = true
teams = true
essentials = false
ultimine = false
backups = false
polyLib = true

[versions]
chunksVersion = "5210496"
baseVersion = "5051953"
questsVersion = "5192381"
teamsVersion = "5176343"
essentialsVersion = "4896152"
ultimineVersion = "5005006"
backupsVersion = "4834403"
polyLibVersion = "5218944"
